/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 drivertext.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function DriverTexting(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/drivertext.glb')
  const { actions } = useAnimations(animations, group)


  useEffect(() => {
    actions.text.play();
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Alpha_Joints002" geometry={nodes.Alpha_Joints002.geometry} material={materials['Alpha_Joints_MAT.002']} skeleton={nodes.Alpha_Joints002.skeleton} />
          <skinnedMesh name="Alpha_Surface" geometry={nodes.Alpha_Surface.geometry} material={materials['Alpha_Body_MAT.002']} skeleton={nodes.Alpha_Surface.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/drivertext.glb')
