/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 workingdriver.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function WorkingDriver(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/workingdriver.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.cards.play();
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Alpha_Joints001" geometry={nodes.Alpha_Joints001.geometry} material={materials['Alpha_Joints_MAT.001']} skeleton={nodes.Alpha_Joints001.skeleton} />
          <skinnedMesh name="Alpha_Surface001" geometry={nodes.Alpha_Surface001.geometry} material={materials['Alpha_Body_MAT.001']} skeleton={nodes.Alpha_Surface001.skeleton} />
        </group>
        <mesh name="Alpha_Joints" geometry={nodes.Alpha_Joints.geometry} material={materials.Alpha_Joints_MAT} />
      </group>
    </group>
  )
}

useGLTF.preload('/workingdriver.glb')
